version: '3.7'

services:
  psql:
    container_name: casinobuddy_psql
    image: postgres:16.2-alpine
    env_file: .env
    ports:
      - 5432:5432/tcp
    expose:
      - "${PUB_PORT:-5432}"
    volumes:
      - casinobuddy_data:/var/lib/postgresql/data

volumes:
  casinobuddy_data:
    external: true
