name: Push

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    strategy:
      matrix:
        rust-version: ["nightly", "stable"]
        cache-key: [""]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: "Install Rust"
      run: |
        rustup toolchain install ${{ matrix.rust-version }} --profile minimal --no-self-update
        rustup install nightly
        rustup default ${{ matrix.rust-version }}
        rustup update
      shell: bash
    - name: Build
      run: cargo +nightly build --verbose
    - name: Clippy
      run: cargo +nightly clippy -- -D clippy::all -D warnings --allow clippy::needless_return -W clippy::pedantic --allow dead_code --allow clippy::unused_asyc
    - name: Run tests
      run: cargo +nightly test --verbose
